### ISSUE TITLE
logo for better identity?

### ISSUE THREAD

**Issue by hutriteguh** [projectcaluma/projectcaluma.github.io#7]
Hey there, I am on a mission to build my graphic design portofolio, if you need a logo, I will gladly making one for you. cheers.

**Comment by hutriteguh** [comment]
Thanks for the brief. Can you provide some logo references how you want the logo to be made?

**Comment by hutriteguh** [comment]
hey @czosel here are some logos I made based on the brief you gave. the chameleon in the logos are subtle made with simple shapes but still look like a chameleon. wdyt?

![image](https://user-images.githubusercontent.com/46064613/52618676-0f869980-2ed2-11e9-9d69-969f5ccd7c9e.png)

![image](https://user-images.githubusercontent.com/46064613/52618686-131a2080-2ed2-11e9-8913-19571a0704cb.png)

![image](https://user-images.githubusercontent.com/46064613/52618646-fc73c980-2ed1-11e9-8186-f5bbed184a96.png)

**Comment by sliverc** [comment]
Thanks @hutriteguh for the logo proposals.:+1:.  My favorite is the eye logo. In terms of colors do you think this could be adjusted to be a bit more colorful (using more than one color)?

Currently on caluma.io we use a greenish color however this can be changed and will certainly be adjusted so it fits the logo.

**Comment by hutriteguh** [comment]
here are some color alternatives @sliverc , I can provide raw .ai file so you can change the color in the future.

![image](https://user-images.githubusercontent.com/46064613/52654263-353c8e80-2f24-11e9-8907-e6b2e96cf425.png)
![image](https://user-images.githubusercontent.com/46064613/52654274-38d01580-2f24-11e9-8e3f-33a789d8f191.png)

**Comment by sliverc** [comment]
@hutriteguh Awesome work. Second line in the middle is certainly my favorite. It would be great to have the ai file but could you also extract as svg?
Also another question: what font are you using and is it allowed to use in a open source context?

**Comment by hutriteguh** [comment]
@sliverc ok I will export all necessary files including .svg
The font is ubuntu by Google Web Font and it is open source. 

Should I make a pull request or just upload the files to google drive and you merge it yourself?

**Comment by sliverc** [comment]
Great. You can adjust the caluma.io page to integrate it if you like, but of course simply uploading to Google Drive and we integrate ourselves is totally fine.

We have to think about how we can add you to the credits (maybe in the footer or so...) - any preference?

Also out of curiosity: How have you heard about Caluma?

**Comment by hutriteguh** [comment]
Great, I'll upload the files to google drive. I don't want to mess the web.

My name in the footer would be lovely.

I searched for projects that I think need graphic materials in github. I am building my graphic design portofolio, so I think doing work like this would be a great practice for me.

**Comment by hutriteguh** [comment]
@sliverc here are the files uploaded to google drive [CALUMA FILES](https://drive.google.com/open?id=1hbPcCmoiOPheVnWDn1fUilDAvG3bMVEi)

Font: [Ubuntu](https://fonts.google.com/specimen/Ubuntu)

let me know if you need anything else.

**Comment by sliverc** [comment]
Great thanks a lot. I have integrated it into our github profile and [twitter](https://twitter.com/projectcaluma). I hope we will be able to integrate it into caluma.io soon.

What credits should we use for the footer? We might also do a tweet - do you have a twitter account we could reference as well?

**Comment by hutriteguh** [comment]
I don't have twitter account. my name Hutri Teguh in the footer is enough.
